name: bunjai_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_gif: ^0.0.4
  lottie: ^3.1.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  reorderables: ^0.6.0
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  http: ^1.2.2
  firebase_auth: ^5.4.0
  flutter_secure_storage: ^9.2.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # ระบุที่อยู่โลโก้ของแอปที่ต้องการ

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/featured_project.jpg
    - assets/images/bg.png
    - assets/images/project01.png
    - assets/images/feed_image.jpg
    - assets/images/animation.gif
    - assets/images/Animation1.json
    - assets/images/Animation2.json
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
